// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2m7KoAnv-Y6-UCtmPyEQ2Fn9DFneUVf0',
    appId: '1:656336911824:web:fa0ac487d434cc06a14dd5',
    messagingSenderId: '656336911824',
    projectId: 'se202-lab-11',
    authDomain: 'se202-lab-11.firebaseapp.com',
    storageBucket: 'se202-lab-11.firebasestorage.app',
    measurementId: 'G-3Z6Q8NMSKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnT8m9zg0WNYpCWpvoE1S2kgLOTcqzvnY',
    appId: '1:656336911824:android:dab1628dd8d0da52a14dd5',
    messagingSenderId: '656336911824',
    projectId: 'se202-lab-11',
    storageBucket: 'se202-lab-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLQrrM_KmYJWrqOGfAKqb3M1_5KuOWVSQ',
    appId: '1:656336911824:ios:fd72d92241644d29a14dd5',
    messagingSenderId: '656336911824',
    projectId: 'se202-lab-11',
    storageBucket: 'se202-lab-11.firebasestorage.app',
    iosBundleId: 'com.example.se202Lab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLQrrM_KmYJWrqOGfAKqb3M1_5KuOWVSQ',
    appId: '1:656336911824:ios:fd72d92241644d29a14dd5',
    messagingSenderId: '656336911824',
    projectId: 'se202-lab-11',
    storageBucket: 'se202-lab-11.firebasestorage.app',
    iosBundleId: 'com.example.se202Lab11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2m7KoAnv-Y6-UCtmPyEQ2Fn9DFneUVf0',
    appId: '1:656336911824:web:6126d08b31a07bbaa14dd5',
    messagingSenderId: '656336911824',
    projectId: 'se202-lab-11',
    authDomain: 'se202-lab-11.firebaseapp.com',
    storageBucket: 'se202-lab-11.firebasestorage.app',
    measurementId: 'G-FCHLZFN5E6',
  );
}
